### ISSUE TITLE
openapi folder

### ISSUE THREAD

**Issue by ifredom** [tnantoka/voivo#16]
I found that the contents in the OpenAPI folder seem to be generated automatically? How did this happen

**Comment by tnantoka** [comment]
@ifredom 

Yes, it was automatically generated by openapi-generator and build_runner from [VOICEVOX's openapi.json](https://github.com/Hiroshiba/voicevox/blob/main/openapi.json).

### Instructions

```
$ brew install openapi-generator
$ openapi-generator generate -i openapi.json -g dart-dio-next -o openapi
$ cd openapi
$ flutter pub get
$ flutter packages pub run build_runner build --delete-conflicting-outputs
```
